CREATE TABLE IF NOT EXISTS `SONGS`
    (
        `ID` CHAR(6) NOT NULL,
        `SONG_TITLE` VARCHAR(32) NOT NULL,
        `COMPOSER` VARCHAR(32),
        `PROJ_DATE` DATE,
        `LAST_EXP` DATE,
        `DAW` VARCHAR(16)
        `ALBUM_ID` CHAR(6),
        `IS_REMIX` BOOLEAN,
        `IS_REMAKE` BOOLEAN,
        `OG_ID` CHAR(6),
        `RELEASE_ID`CHAR(6),
    PRIMARY KEY ( `ID` )
    );

CREATE TABLE IF NOT EXISTS `VOCALISTS`
    (
        `ID` CHAR(6) NOT NULL,
        `NAME` VARCHAR(32),
        `SOFTWARE` VARCHAR(32),
        `IS_AI` BOOLEAN,
        `VOICE_PROVIDER` VARCHAR(32),
    PRIMARY KEY ( `ID` )
    );

CREATE TABLE IF NOT EXISTS `ALBUMS`
    (
        `ID` CHAR(6) NOT NULL,
        `TITLE` VARCHAR(32),
        `RELEASE_DATE` DATE,
        `RELEASE_ID` CHAR(6),
    PRIMARY KEY ( `ID` )
    );

CREATE TABLE IF NOT EXISTS `SONG_ALBUM`
    (
        `ID` CHAR(6) NOT NULL,
        `ALBUM_ID` CHAR(6) NOT NULL,
        `SONG_ID` CHAR(6) NOT NULL,
    PRIMARY KEY ( `ID` ),
    FOREIGN KEY ( `ALBUM_ID` ) REFERENCES `ALBUMS` ( `ID` )
        ON DELETE CASCADE,
    FOREIGN KEY ( `SONG_ID` ) REFERENCES `SONGS` ( `ID` )
        ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS `SONG_VOCALIST`
    (
        `ID` CHAR(6) NOT NULL,
        `SONG_ID` CHAR(6) NOT NULL,
        `VOCALIST_ID` CHAR(6) NOT NULL,
    PRIMARY KEY ( `ID` ),
    FOREIGN KEY ( `SONG_ID` ) REFERENCES `SONGS` ( `ID` )
        ON DELETE CASCADE,
    FOREIGN KEY ( `VOCALIST_ID` ) REFERENCES `VOCALISTS` ( `ID` )
        ON DELETE CASCADE
    )